spring.application.name=task-management-service
server.port=8090
# R2DBC Database Configuration
spring.r2dbc.url=r2dbc:postgresql://localhost:5432/task-management
spring.r2dbc.username=gondasatishkumar
spring.r2dbc.password=
spring.r2dbc.pool.initial-size=10
spring.r2dbc.pool.max-size=20
# Logging
logging.level.root=INFO
logging.level.com.example.task=DEBUG